namespace body;

// bundle chunk and bundle
table BundleChunk
{
    id: ulong;
    compressed_size: uint;
    decompressed_size: uint;
}

table Bundle
{
    id: ulong;
    chunks: [BundleChunk];
}

// language
table Lang
{
    id: byte;
    name: string;
}

// file
table File
{
    id: ulong;
    dir_id: ulong;
    size: ulong;
    name: string;
    lang_flags: ulong;
    unknown5: byte; 
    unknown6: byte; 
    chunk_ids: [ulong];
    unknown8: byte;
    link: string;
    unknown10: byte; 
    chunk_param_index: byte;
    permission: byte;
}

// dir
table Dir
{
    id: ulong;
    parent: ulong;
    name: string;
}

// encrypt key
table EncryptKey
{
    unknown: byte;
}

// chunk param
table ChunkParam
{
    id: ushort;
    version: byte;
    min_chunk_size: uint;
    max_chunk_size: uint;
    max_decompressed_size: uint;
}

// body
table Body
{
    bundles: [Bundle];
    langs: [Lang];
    files: [File];
    dirs: [Dir];
    encrypt_keys: [EncryptKey];
    chunk_params: [ChunkParam];
}

root_type Body;